set nocompatible

filetype on
filetype plugin on
filetype indent on

syntax on
set number
set cursorline

set tabstop=2
set shiftwidth=2
set expandtab

set smartcase
set showmode
set hlsearch
set showmode

set autoindent
set smartindent
filetype plugin indent on

inoremap jk <Esc>

inoremap ( ()<Left>
inoremap (<CR> (<CR>)<Esc>O
inoremap [ []<Left>
inoremap [<CR> [<CR>]<Esc>O
inoremap { {}<Left>
inoremap {<CR> {<CR>}<Esc>O
inoremap ' ''<Left>
inoremap '' ''''<Left><Left>
inoremap ''<CR> ''<CR>''<Esc>O
inoremap " ""<Left>

